# Generated by Django 3.0b1 on 2020-06-25 07:32

import auditorium.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditorium', '0003_auto_20200625_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditoriumreservation',
            name='status',
            field=models.CharField(choices=[(auditorium.models.AuditoriumStatus['PENDING'], 'Pending'), (auditorium.models.AuditoriumStatus['APPROVED'], 'Approved'), (auditorium.models.AuditoriumStatus['REJECTED'], 'Rejected')], default='PENDING', max_length=10),
        ),
    ]
