# Generated by Django 3.0b1 on 2020-06-01 06:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_auto_20200513_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['created_on']},
        ),
        migrations.RemoveField(
            model_name='comments',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='commented_at',
        ),
        migrations.RemoveField(
            model_name='comments',
            name='publisher',
        ),
        migrations.AddField(
            model_name='comments',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='comments',
            name='body',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='comments',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 1, 6, 33, 11, 74210, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='comments',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AddField(
            model_name='comments',
            name='name',
            field=models.CharField(default=None, max_length=80),
        ),
    ]
